export const githubStackSource = {
  url: "https://github.com/Kynmmarshall/Kynmmarshall#-tech-snapshot",
  reviewedOn: "2026-09-05",
  technologies: [
    "Dart",
    "Flutter",
    "React",
    "Python",
    "JavaScript",
    "Node.js",
    "Django",
    "FastAPI",
    "Flask",
    "C",
    "C++",
    "GLSL",
    "Swift",
    "HTML5",
    "CSS3",
    "CMake",
    "TeX",
    "Git",
    "GitHub",
    "Jenkins",
    "Flame",
    "Pygame",
    "graphics.h",
    "Tiled",
    "GitHub Actions",
    "UML",
    "Docker",
    "Kubernetes",
    "MySQL",
    "PostgreSQL",
    "TypeScript",
    "Java",
    "OpenGL",
    "Custom C++ engine",
  ],
} as const;

export const profileListedTools: readonly string[] = [
  "Django",
  "FastAPI",
  "Flask",
  "Swift",
  "Docker",
  "Kubernetes",
  "MySQL",
  "CMake",
  "TeX",
  "OpenGL",
  "GLSL",
  "Custom C++ engine",
  "Observability",
  "Backups",
  "Security hardening",
];
